export const GET_TASKS = '/todos'
export const GET_COUNTERS = '/counters'
export const ADD_TASK = '/addtodo'
export const EDIT_TASK = '/edit'
export const DELETE_TASK = '/delete'
export const CLEAR_COMPLETED_TASKS = '/clearcompleted'
export const CHANGE_TASKS_STATUSES = '/changestatuses'
